---
title: "Machine learning for the cognitive sciences"
subtitle: "Master Program in Cognitive Sciences, UCR"
output: github_document
editor_options: 
  chunk_output_type: console
date: '2024-12-01'
---

<div class="alert alert-success">

<center>[**Check the 2024 course website for materials and practices (in spanish)**](https://marce10.github.io/aprendizaje_estadistico_2024/)</center>

</div>

Machine learning is a branch of artificial intelligence focused on developing algorithms and models that enable computers to learn patterns and make predictions for data-driven decision-making. Instead of following explicit instructions to perform a task, these algorithms identify patterns in data and use them to improve their performance on specific tasks. Statistical learning is applied in a wide range of areas, from voice recognition to analyzing large datasets and automating industrial processes. In this course, students will learn the fundamentals and basic techniques of statistical learning to address research questions in Cognitive Sciences.

::: {.alert .alert-info}

### **Objectives** {.unnumbered .unlisted}

- Describe and explain the main concepts and methods of statistical learning applied to Cognitive Sciences.
- Differentiate between types of computational learning: supervised, unsupervised, semi-supervised, and reinforcement learning.
- Understand the theoretical foundations and assumptions of techniques such as regression, neural networks, decision trees, and cluster analysis.
- Implement the techniques developed throughout the course in the R programming language.
- Select the most appropriate technique based on practical problems or research questions in various areas of Cognitive Sciences.



:::

&nbsp; 


