---
title: "Tools for Reproducible Research"
subtitle: "OTS, 2024 REU program"
output: github_document
editor_options: 
  chunk_output_type: console
date: '2024-05-01'
---

<div class="alert alert-success">

<center>[**Check the 2024 course website for materials and practices**](https://marce10.github.io/OTS_REU_OS_2024/)</center>

</div>

Scientific production currently suffers from a lack of reproducibility (the ability to recreate a study based on published information), due to the poor documentation of the methods and analyses used, as well as the lack of access to the data generated. Biology has not escaped this crisis of scientific reproducibility, which affects the credibility of our community. Fortunately, in response to this crisis, a multitude of tools have been developed, in most cases freely available, to increase the transparency and accessibility of data supporting the conclusions of scientific studies. Making these tools available to the scientific community and encouraging their use early in the training of researchers is critical to solving the reproducibility crisis. These tools revolve around three main axes: 1) online repositories for sharing data and research products, 2) open access digital tools, and 3) the implementation of good data management and analysis practices. These three axes represent the modules in which the workshop is organized. This workshop aims to deepen the use of tools (mostly digital) as well as good practices along each of the common stages of the each of the stages common to the development of research projects in biology.

::: {.alert .alert-info}
### **Objectives** {.unnumbered .unlisted}

- To raise awareness of the current problem of scientific reproducibility and its implications for the production of knowledge and its legitimacy in society
- To provide students with free software computational tools that facilitate the documentation and accessibility of research
- Identify processes at different stages of scientific research where practices that facilitate reproducibility can be adopted
- Provide students with experience in applying the tools provided through practices

:::

&nbsp; 


