---
title: "Advanced R (for undergrads)"
subtitle: "Advanced R programming and data visualization"
output: github_document
editor_options: 
  chunk_output_type: console
date: '2024-06-01'
---

<div class="alert alert-success">

<center>[**Check the 2024 course website for materials and practices** (in spanish)](https://marce10.github.io/r_avanzado_2024)</center>

</div>

This course aims to deepen in the elements of computer programming, database manipulation, experimental design, custom graphing, and the use of advanced statistical modeling and techniques using R as a platform. The course is intended for advanced undergraduate or graduate students. The course aims to cover the basics of the main statistical analysis and modeling techniques, as well as emerging analyses. Every week there will be laboratory practices where the concepts developed during the theory classes will be applied. In addition, during the course each student will present a package or extension (set of tools applicable to specific analysis) of R, where he/she will deepen on its applications in the field of biology demonstrating in class what the analysis consists of.

::: {.alert .alert-info}
### **Objectives** {.unnumbered .unlisted}

- Familiarize the student with R programming
- Provide tools for database manipulation.
- Use diverse data visualization methods
- Provide students with experience in the application of the tools provided through internships and research projects

:::

&nbsp; 


